plugins:
  - "@dotcom-tool-kit/component"
  - "@dotcom-tool-kit/eslint"
commands:
  test:local:
    - Eslint
  test:ci:
    - Eslint
options:
  plugins:
    '@dotcom-tool-kit/circleci':
      cimgNodeVersions:
        - '22.9'
        - '20.17'
        - '18.20'
