sudo: false
language: node_js
script: npm test
node_js:
- '0.10'
before_deploy:
- npm-prepublish --verbose
deploy:
  provider: npm
  email: strategic.products@ft.com
  api_key:
    secure: XasmdIfN8P49WV6ok0yuqGMg2e8d2n6u8R5Q/Yrp7IEWE2DT11ajzPy8vEhMpTT5tLs4J/bsOl5Y5CSgC3+DMNtCooQLakZqpv+7ZSwbrnHa6lsnZ6IwCWpLi9jRfkVZnKh99yNhjr5ZlZXCnj2mQgn9ZAd07+P2t6UA49gcrNY=
  on:
    tags: true
    repo: Financial-Times/next-metrics
