sudo: false
language: node_js
script: npm test
node_js:
- 0.12.2
before_deploy:
- npm-prepublish --verbose
deploy:
  provider: npm
  email: strategic.products@ft.com
  api_key:
    secure: f95ylL74ovVxcTkHkOh22nDL8IhYh03cWQJYufkqeGp047Fv6aoOZRymHQ4FHX0cp11idT8am9P81Gm0Ae8vrUblsgFEZ8Z0tzD+lT7OyrYmMM+cN61fDxFJkJDXVC4ybqwraDsQ+M3bAmS/XWobaHim6gD7jwphH+KHNf5Vv70=
  on:
    tags: true
    repo: Financial-Times/next-metrics
