sudo: false
language: node_js
script: npm test
node_js:
- '0.10'
before_deploy:
- npm-prepublish --verbose
deploy:
  provider: npm
  email: strategic.products@ft.com
  api_key:
    secure: OjGKMTDFb9SJx39NRMg+Vj0wJ/dnY9DXGqh2MsuRRbFEA4hBHutphnTvXBiOEE8r4fZ12osrC2+Zo2/oerJMZEYvL+pkpwQSNon4597znNzXcg6l7TbXZhW0a2plPPNXkUhH+B2BQp5n4/a9CGjmueinoHeXbdqeqMDTrVn+4/8=
  on:
    tags: true
    repo: Financial-Times/next-metrics
